[package]
name = "key_capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12.1"
xkbcommon = { version = "0.6", features = ["x11"] }
