# Keylogger default config

title = "Keylogger config"

[physical_layout]
raw_0 = [[143, 1], [29, 1], [125, 1], [56, 1], [57, 5], [100, 1], [99, 1], [97, 1], [104, 1], [103, 1], [109, 1]]
raw_1 = [[42, 4], [86, 5], [44, 5], [45, 5], [46, 5], [47, 5], [48, 5], [49, 5], [50, 5], [51, 5], [52, 5], [53, 2],[54, 5]]
raw_2 = [[1, 4], [30, 2], [31, 2], [32, 2], [33, 2], [34, 2], [35, 2], [36, 2], [37, 2], [38, 2], [39, 2], [40, 2], [43, 2], [28, 2]]
raw_3 = [[15, 3], [16, 2], [17, 2], [18, 2], [19, 2], [20, 2], [21, 2], [22, 2], [23, 2], [24, 2], [25, 2], [26, 2], [27, 2], [28, 3]]
raw_4 = [[41, 1], [2, 1], [3, 1], [4, 1], [5, 1], [6, 1], [7, 1], [8, 1], [9, 1], [10, 1], [11, 1], [12, 1], [13, 1], [14, 3]]
raw_5 = [[1, 3], [59, 2], [60, 2], [61, 2], [62, 2], [63, 2], [64, 2], [65, 2], [66, 2], [67, 2], [68, 2], [87, 2], [88, 2], [102, 2], [107, 2], [110, 2]]

[keybindings]
PrevTab = "w"
NextTab = "f"
PrevLayer = "h"
NextLayer = "i"
SelectKeyMode = "m"
ToggleHeatmap = "g"
ShowOneKeyWindow = "k"
ShowLayerWindow = "l"
ToggleHelp = "?"
RefreshData = "r"
Quit = "q"

[typing_layout]
Path = "/usr/share/x11/xkb/symbols/cuco"

[deamon]
SaveInterval = 5
